services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment :
      POSTGRES_USER: jbw
      POSTGRES_PASSWORD: admin
      POSTGRES_DATABASE: Produit



  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8080:8080'